# 在cpu上简单的张量示例

In [9]:
import torch

x = torch.tensor([[1, 2, 3], [4, 5, 6]])
y = torch.tensor([[7, 8, 9], [10, 11, 12]])
z = x + y
print(z)
print(z.size())
print(z.device)

tensor([[ 8, 10, 12],
        [14, 16, 18]])
torch.Size([2, 3])
cpu


# 在gpu上简单的张量示例

In [10]:
import torch
device = "cuda" if torch.cuda.is_available() else "cpu"
x = torch.tensor([[1, 2, 3], [4, 5, 6]], device=device)
y = torch.tensor([[7, 8, 9], [10, 11, 12]], device=device)
z = x + y
print(z)
print(z.size())
print(z.device)

tensor([[ 8, 10, 12],
        [14, 16, 18]], device='cuda:0')
torch.Size([2, 3])
cuda:0


# 在cpu和gpu之间移动张量

In [11]:
device = "cuda" if torch.cuda.is_available() else "cpu"
x = x.to(device)
y = y.to(device)
z = x + y
print(z)
print(z.device)

z = z.to("cpu")
print(z)
print(z.device)

tensor([[ 8, 10, 12],
        [14, 16, 18]], device='cuda:0')
cuda:0
tensor([[ 8, 10, 12],
        [14, 16, 18]])
cpu


## 说明
- 通过`tensor.to(device)`或者`tensor.cuda()`可以将张量移动到指定的设备上
- 通过`tensor.to("cpu")`可以将张量移动到cpu上
- 通过`tensor.device`可以查看张量所在的设备
- 通过`torch.cuda.is_available()`可以判断cuda是否可用
- 通过`torch.device("cuda")`可以指定cuda设备
- 通过`torch.tensor(..., device="cuda:0")`可以在创建张量的时候就指定设备
- 通过`torch.cuda.empty_cache()`可以清理显存
- 通过`torch.cuda.memory_allocated()`可以查看已使用的显存大小
- 通过`torch.cuda.memory_cached()`可以查看显存中缓存的数据大小
- 通过`torch.cuda.max_memory_allocated()`可以查看曾经使用过的显存的最大值
- 通过`torch.cuda.max_memory_cached()`可以查看显存中缓存的数据的最大值
- 通过`torch.cuda.reset_max_memory_allocated()`可以重置曾经使用过的显存的最大值
- 通过`torch.cuda.reset_max_memory_cached()`可以重置显存中缓存的数据的最大值
其中，可以直接使用字符串作为设备参数，而不是设备对象，如`tensor.to("cuda:0")`。
因此，以下代码都是等价的：
- device = "cuda"
- device = "cuda:0"
- device = torch.device("cuda")
- device = torch.device("cuda:0")

In [13]:
import torch
print(torch.cuda.memory_usage())

1


In [14]:
import torch
print(torch.cuda.memory_allocated())

1024
