# 创建张量

## (1) 由一个列表创建张量

In [2]:
import numpy
import torch
# Created from preexisting arrays
w = torch.tensor([1,2,3])
print(w)

tensor([1, 2, 3])


## (2) 由一个元组创建张量

In [3]:
import torch
w = torch.tensor((1,2,3))
print(w)

tensor([1, 2, 3])


## (3) 由一个numpy数组创建张量

In [5]:
import numpy
import torch
w = torch.tensor(numpy.array([1,2,3]))
print(w)

tensor([1, 2, 3])


Initialized by size

## (4) 未初始化，元素值不可预测

In [6]:
import numpy as np
import torch
w = torch.empty(3,3)
print(w)

tensor([[-7.9103e-04,  4.5884e-41,  4.0878e-34],
        [ 0.0000e+00, -3.4161e-06,  4.5883e-41],
        [-2.8501e+13,  1.1085e+26, -3.7409e-06]])


## (5) 所有元素初始化为0.0

In [7]:
import numpy
w = torch.zeros(3,3)
print(w)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
